config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  resources :categories
  devise_for :admins

  devise_for :users
  resources :users do
    resources :order_items
    resources :orders
  end
  resources :subscriptions, only: [:new, :create]
  get 'thanks', to: 'charges#thanks', as: 'thanks'
  resources :orders do
    get "checkout"
    get "cart"
    get "shipping"
    post "tracking"
  end
  resources :order_items
  resources :addresses
  resources :products do
    get "delete"
    get "delivery"
  end
  match '/update_currency' => 'application#update_currency', as: :update_currency, :via => :get
  resources :images
  resource :cart, only: [:show]
  resources :charges, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items, dependent: :destroy
  before_save :update_total
  before_create :update_status
  has_one :address
  register_currency :sgd


  def calculate_total(currency)
    self.order_items.collect { |item| Money.new(item.product.price, "SGD").exchange_to(currency.upcase) * item.quantity }.sum
  end

  def calculate_sgd_total
    self.order_items.collect { |item| item.product.price * item.quantity }.sum
  end

  def calculate_usd_total
    self.order_items.collect { |item| Money.new(item.product.price, "SGD").exchange_to("USD") * item.quantity }.sum
  end

  private

  def update_status
    if self.status == nil?
      self.status = "In progress"
    end
  end

  def update_total
    current_currency=ApplicationController.helpers.current
    self.total_price = calculate_total(current_currency)
    self.currency_total = current_currency
  end


end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include ChargesHelper

  skip_before_action :verify_authenticity_token

  before_action :check_user, only: [:index, :show, :edit, :update, :destroy]


  # GET /orders
  # GET /orders.json
  def index
    if user_signed_in?
      @orders = current_user.account.orders
    elsif admin_signed_in?
      @orders=Order.all()
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order=Order.find(params[:id])
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @order.currency_total = current_currency

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def checkout
    @order_total_currency_price=current_order.calculate_total(current_currency)
    @freeShippingAmount = freeShippingAmountCurrency
    @address = Address.new()
    @order=Order.find(current_order)
    render :layout=>'order_layout'
  end

  def cart
    @order_total_currency_price=current_order.calculate_total(current_currency)
    @order=Order.find(current_order)
    @freeShippingAmount = freeShippingAmountCurrency
    render :layout=>'order_layout'
  end

  def shipping
    shipment=EasyPost::Shipment.retrieve(current_order.shipment_id)

    @rates=shipment.rates
    @rates = @rates.each{|h| h.rate = Money.default_bank.exchange((h.rate), h.currency.upcase , current_currency.upcase)}
    @lowest_rate=Money.new((@rates.min_by{|h| h.rate}.rate), (@rates.min_by{|h| h.rate}.currency))
    @order=current_order
    @zero_object=Money.new(0,current_currency.upcase)
    order = Order.find(current_order)
    if !@order.order_items.any? {|order_item| order_item.product.category_id=="3" }
      totalship = @zero_object
      selected_rate = params[:selected_rate] ? (Money.new((@rates.select {|e| e.id == params[:selected_rate]}[0].rate),(@rates.select {|e| e.id == params[:selected_rate]}[0].currency.upcase))) : nil
      if current_order.total_price >= 200
        totalship= selected_rate ? (selected_rate-@lowest_rate) : @lowest_rate
      else
        totalship= params[:selected_rate] ? selected_rate : @lowest_rate
      end
      if params[:selected_rate]
        @shipping=((current_order.total_price)>=200 && selected_rate==@lowest_rate) ? @zero_object : totalship
      else
        @shipping=((current_order.total_price)>=200 ? @zero_object : totalship)
      end
      @order_total= current_order.calculate_total(current_currency.upcase)

      @total = @shipping + @order_total
      @total100 = @total
      order.total_shipping=totalship
      order.total_shipping_currency=totalship.currency.iso_code
      order.selected_rate = params[:selected_rate] ? params[:selected_rate] : @rates.min_by{|h| h[:rate]}.id
      order.save!
    end
    @address=Address.find_by("id = ?", current_order.address_id)
    if order.save
      respond_to do |format|

        format.html
        #I'm assuming its js request
      end
    end
  end

  def tracking
    request_string = request.body.read
    parsed_request = JSON.parse(request_string)

    if parsed_request['object'] == 'Event' && parsed_request['description'] == 'tracker.updated'
      event = EasyPost::Event.receive(request_string)
      tracker = event.result

      message = "Hey, this is FunCompany."
      if tracker.status == 'delivered'
        message += "Your package has arrived! "
      else
        message += "There's an update on your package: "
      end

      td = tracker.tracking_details.reverse.find{ |tracking_detail| tracking_detail.status == tracker.status }
      message += "#{tracker.carrier} says: #{td.message} in #{td.tracking_location.city}." if td.present?

      order=Order.find(params[:order_id])

      TrackerUpdateJob.set(wait: 20.seconds).perform_later(order.customer_email, message)
      # from = SendGrid::Email.new(email: 'test@fromaddress.com')
      # subject = 'Hello World from the SendGrid Ruby Library!'
      # to = SendGrid::Email.new(email: 'customer@gmail.com')
      # content = SendGrid::Content.new(type: 'text/plain', value: message)
      # mail = SendGrid::Mail.new(from, subject, to, content)
      #
      # output = settings.sendgrid.client.mail._("send").post(request_body: mail.to_json)

      [200, {}, "Email update was sent to the customer!"]
    else
      [200, {}, "Not a Tracker event, so nothing to do here for now..."]
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      # @order = Order.find(params[:id])
    end

    def check_user
      if admin_signed_in?
      else
        set_order
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:status, :account_id, :total_price)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(order) do |f| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status %>
    <%= f.text_field :status %>
  </div>

  <div class="field">
    <%= f.label :account_id %>
    <%= f.number_field :account_id %>
  </div>

  <div class="field">
    <%= f.label :total_price %>
    <%= f.text_field :total_price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/cart.html.erb
<div class="cart-page">
  <div class="container checkout-content" id="content">
    <div class="big wrapper col-xs-12" id="order-summary-content">
      <div class="">
        <div class="btn-container return-to-shop-container col-xs-12">
          <a href="<%= request.base_url %>/categories/2/?low=0&high=400&tags%5B%5D=Bracelet&tags%5B%5D=Earring&tags%5B%5D=Necklace&tags%5B%5D=Ring" class="link_to btn btn-lg simple-button-black" id="continue-shopping">
            <span class="button-text-black">Return To Shop</span>
          </a>
        </div>
        <div class="checkout-progress-container">
          <div class="checkout-progress col-xs-12">
            <div class="span progress-bar-item col-xs-3 text-center cart-step" id="current-step-item"><span>Cart Checkout</span></div>
            <div class="span progress-bar-item col-xs-3 text-center shipping-step"><span>Shipping</span></div>
            <div class="span progress-bar-item col-xs-3 text-center payment-step"><span>Payment</span></div>
            <div class="span progress-bar-item col-xs-3 text-center"><span>Confirmation</span></div>
          </div>
          <div class="checkout-progress-count col-xs-12">
            <div class="span progress-bar-number col-xs-3 text-center cart-step-number" id="current-step-number"><span class="number-field">1</span></div>
            <div class="span progress-bar-number col-xs-3 text-center shipping-step-number"><span class=" number-field second-step-number">2</span></div>
            <div class="span progress-bar-number col-xs-3 text-center payment-step-number"><span class="number-field">3</span></div>
            <div class="span progress-bar-number col-xs-3 text-center"><span class="number-field">4</span></div>
          </div>
          <div class="animation-row checkout-progress-count">
            <div class="progress-bar-number animation-stop first-stop col-xs-3 text-center">
              <i class="fa fa-shopping-bag shopping-bag-icon" id="shopping-bag-icon" aria-hidden="true"></i>
              <span class="band" id="conveyorBelt"></span>
            </div>
            <div class="progress-bar-number animation-stop second-stop col-xs-3 text-center">
              <div class="truck-icon-container">
                <div class="shipping-stop truck-icon" id ="truck-icon">
                  <div class="truck-loading"></div>
                  <span class="truck-name">Xpress</span>
                  <div class="truck-front"></div>
                  <div class="truck-window"></div>
                  <div class="truck-wheel back"></div>
                  <div class="truck-wheel front"></div>
                </div>
              </div>
            </div>
            <div class="progress-bar-number animation-stop third-stop col-xs-3 text-center">
              <div class="payment-stop">
                <div class="toll-box"></div>
                <div class="toll-window"></div>
                <span class="toll-name">Toll</span>
                <div class="gate">
                  <div class="gate-pillar"></div>
                  <div class="gate-bar"></div>
                </div>
              </div>
            </div>
            <div class="progress-bar-number animation-stop fourth-stop col-xs-3 text-center">
            </div>
          </div>
        </div>
        <div class="cart-info cart-page-content">
          <div class="section-title-container checkout-title-container col-xs-12">
            <span class="section-title">Shopping Cart</span>
          </div>
          <table class="cart-table">
            <tr class="title-row">
              <th class="small-column"></th>
              <th class="checkout-tab-item">Name</th>
              <th class="checkout-tab-item">Size</th>
              <th class="checkout-tab-item">Unit Price</th>
              <th class="checkout-tab-item">Qty</th>
              <th class="checkout-tab-item">Total Price</th>
              <th class="small-column"></th>
            </tr>
            <tr class="spacer"></tr>
            <div class="order-item-rows">
              <%if @order.order_items.any?%>
                <%@order.order_items.each do |order_item|%>
                  <tr class="between-product-spacer"></tr>
                  <tr class="product-info-row">
                    <td>
                    </td>
                    <td>

                    </td>
                    <td>

                    </td>
                    <td>

                    </td>
                    <td>
                      <%= image_tag(order_item.product.images.first.photo.url, :class=> "checkout-cart-item-image") %>
                    </td>
                    <td colspan="2" class="very-small-screen-product-name-size">
                      <span class="checkout-name-container block">
                        <span class="small-text checkout-product-name">
                          <%=order_item.product.name%>
                        </span>
                      </span>
                      <span class="very-small-screen-size-and-price block">
                        <span class="small-screen-size-container inline text-left">
                          <span class="small-text" id="very-small-screen-size">
                            Size: <%=order_item.product.size%>cm
                          </span>
                        </span>
                        <span class="small-screen-unit-price-container block text-left">
                          <span class="small-text" id="very-small-screen-price">
                            Price: <%=humanized_money_with_symbol order_item.product.currency_price("#{current_currency}") %>
                          </span>
                        </span>
                      </span>
                    </td>
                  </tr>

                  <tr class="same-product-spacer"></tr>
                  <tr class="quantity-and-total-row">
                    <td class="small-column"></td>
                    <td class="checkout-tab-item">Name</td>
                    <td class="checkout-tab-item">Size</td>
                    <td class="checkout-tab-item">Unit Price</td>
                    <td class="checkout-tab-item">Qty</td>
                    <td class="checkout-tab-item">Total Price</td>
                    <td class="small-column"></td>
                  </tr>
                  <tr class="order-item-row" id=<%=order_item.id%>>
                    <div class="order-item">
                      <div class="checkout-details">
                        <td class="image-and-info-column">
                          <%= image_tag(order_item.product.images.first.photo.url, :class=> "checkout-cart-item-image") %>

                        </td>
                        <td class="product-info-column">
                          <span class="checkout-name-container">
                            <span class="small-text checkout-product-name">
                              <%=order_item.product.name%>
                            </span>
                          </span>
                          <span class="small-screen-size-container">
                            <span class="small-text" id="very-small-screen-size">
                              Size: <%=order_item.product.size%>cm
                            </span>
                          </span>
                          <span class="small-screen-unit-price-container">
                            <span class="small-text" id="very-small-screen-price">
                              Unit Price: <%=humanized_money_with_symbol order_item.product.currency_price("#{current_currency}") %>
                            </span>
                          </span>
                        </td>
                        <td>
                          <span class="small-text">
                            <%=order_item.product.size%>cm
                          </span>
                        </td>
                        <td>
                          <span class="small-text"><%=humanized_money_with_symbol order_item.product.currency_price("#{current_currency}") %></span>
                        </td>

                        <td>
                          <%= form_for order_item, remote: true, :id=>"checkout-update-item" do |f| %>
                            <div class="cart-form">
                              <%= f.hidden_field :product_id, :class=>"product_id", value: order_item.product.id %>
                              <%= f.hidden_field :order_item_id, :class=>"order_item_id", value: order_item.id %>
                              <%= f.hidden_field :order_item_quantity, :class=>"order_item_quantity", value: order_item.quantity %>
                              <div class="cart-notice"></div>
                              <div class="minus-quantity checkout-minus-quantity" data-href = "<%=order_item.id%>"><span>-</span></div>
                              <%= f.number_field :quantity, :class=>"jewelery-quantity checkout-quantity small-text #{order_item.id}" , id:order_item.id, :"data-href" => order_item.product.stock, :placeholder=>order_item.quantity %>
                              <div class="plus-quantity checkout-plus-quantity" data-href = "<%=order_item.id%>"><span>+</span></div>
                            </div>
                          <%end%>
                        </td>

                        <td>
                          <span class="total_price_per_product small-text <%=order_item.id%>"><%=humanized_money_with_symbol order_item.product.currency_price("#{current_currency}")* order_item.quantity%></span>
                        </td>

                        <td>
                          <span class="item-center">
                            <%= link_to order_item_path(order_item), :data => {:method => "delete"}, remote: true, :class =>"delete_order_item_checkout link_to", :"data-href"=> order_item.id do%>
                              <span class="remove-text"><i class="fa fa-trash" aria-hidden="true"></i><span class="remove-text">Remove</span></span>
                            <%end%>
                          </span>
                        </td>
                      </div>
                    </div>
                  </tr>
                  <tr class="between-product-spacer"></tr>
                  <tr class="spacer"></tr>
                <%end%>
              <%else%>
                <tr><td colspan="7" class="cart-empty-"><span class="cart-empty">Your Cart is Empty</span></td></tr>
              <%end%>
            </div>
          </table>
          <div class="border-bottom"></div>
          <div class="sub-total col-xs-12">
            <span class="subtotal-text">
              Subtotal
            </span>
            <span class="order-total-container">
              <span class="sub-total-number">
                <%=humanized_money_with_symbol current_order.calculate_total("#{current_currency}")%>
              </span>
            </span>
          </div>
          <div class="btn-container col-xs-12">
            <%if @order.order_items.any?%>
              <%= button_tag :class=>"btn btn-lg simple-button-black final-checkout",:"data-href" => @order.id, :id=>"final-checkout" do %>
                <span class="button-text-black">
                  Proceed to checkout<i class='hi hi-angle-right proceed-icon'></i>
                </span>
              <%end%>
            <%end%>
          </div>
          <div class="till-free-ship">
            <%if @order_total_currency_price < @freeShippingAmount%>
              <span class="small-text">Spend an extra <%=humanized_money_with_symbol @freeShippingAmount-current_order.calculate_total("#{current_currency}")%> and receive free shipping</span>
            <%else%>
              <span class="small-text">You receive free shipping for this order</span>
            <%end%>
          </div>
          <div class="shipping-div">
            <span class="free-shipping-text">Free Shipping on all orders above US$200</span>
          </div>
        </div>
      </div>
    </div>
    <div id="shipping-content">
    </div>
  </div>
</div>

app/views/orders/checkout.js.erb
$("#product-modal").html("<%= escape_javascript(render 'checkout') %>")
$("#product-modal").modal("show")

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <%if user_signed_in?%>
    <h1>My Orders</h1>
  <%elsif admin_signed_in?%>
    <h1>All Order</h1>
  <%end%>
  <% @orders.each do |order|%>
    <%= link_to order_path(order), remote: true do %>
      <div class="col-md-12 order">
        <div class="col-md-2">
          <%=order.status%>
        </div>
        <div class="col-md-2">
          <%=order.total_price%>
        </div>
        <div class="col-md-4">
          <%order.order_items.each do |order_item|%>
            <div class="col-md-12">
              <%=order_item.quantity%> x
              <%=order_item.product.name%>
              <%if order_item.product.category_id=="1"%>
                (<%=order_item.size%>g)
              <%else%>
                (<%=order_item.product.size%>cm)
              <%end%>
            </div>
          <%end%>
        </div>
      </div>
    <%end%>
  <%end%>
</div>
<div id="order-modal" class="modal"></div>

app/views/orders/old-new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/shipping.html.erb
<div class="big wrapper">
  <div class="col-xs-12 company-logo-checkout-container">
    <%= image_tag("necklaces.jpg", :class => "company-logo-checkout") %>
  </div>
  <div class="checkout-progress-container">
    <div class="checkout-progress col-xs-12">
      <%= link_to order_cart_path(current_order), class: "", id:"" do %>
        <div class="span progress-bar-item col-xs-3 text-center"><span>Cart Checkout</span></div>
      <%end%>
      <%= link_to order_checkout_path(current_order), class: "", id:"" do %>
        <div class="span progress-bar-item col-xs-3 text-center"><span>Shipping</span></div>
      <%end%>
      <div class="span progress-bar-item col-xs-3 text-center" id="current-step-item"><span>Payment</span></div>
      <div class="span progress-bar-item col-xs-3 text-center"><span>Confirmation</span></div>
    </div>
    <div class="checkout-progress-count col-xs-12">
      <%= link_to order_cart_path(current_order), class: "", id:"" do %>
        <div class="span progress-bar-number col-xs-3 text-center"><i class="fa fa-check-circle" aria-hidden="true"></i></div>
      <%end%>
      <%= link_to order_checkout_path(current_order), class: "", id:"" do %>
        <div class="span progress-bar-number col-xs-3 text-center"><i class="fa fa-check-circle" aria-hidden="true"></i></div>
      <%end%>
      <div class="span progress-bar-number col-xs-3 text-center" id="current-step-number"><span>3</span></div>
      <div class="span progress-bar-number col-xs-3 text-center"><span>4</span></div>
    </div>
    <img class="securePayment" src="//st0.mngbcn.com/images/checkout/SecurePayment.jpg">
  </div>
  <div class="shipping-content">
    <div class="sidecart-container">
      <div class="section-title-container checkout-title-container">
        <span class="section-title" id="shopping-cart-checkout-title">Shopping Cart</span>
      </div>
      <%= link_to order_cart_path(current_order), class: "btn btn-lg simple-button-black", id:"return-to-cart" do %>
        <span class="button-text-black">
          Edit Cart
        </span>
      <%end%>
      <table class="checkout-table">
        <tr class="title-row">
          <th class="small-column"></th>
          <th class="checkout-tab-item">Name</th>
          <th class="checkout-tab-item">Qty</th>
          <th class="checkout-tab-item">Total Price</th>
        </tr>
        <tr class="spacer"></tr>

        <%@order.order_items.each do |order_item|%>
          <tr class="order-item-row" id=<%=order_item.id%>>
            <div class="order-item">
              <div class="checkout-details">
                <td>
                  <%= image_tag(order_item.product.images.first.photo.url, :class=> "checkout-cart-item-image") %>
                </td>
                <td>
                  <span class="checkout-name-container">
                    <span class="small-text checkout-product-name">
                      <%=order_item.product.name%>
                    </span>
                  </span>
                </td>
                <td>
                  <span class="small-text">
                    <%=order_item.quantity%>
                  </span>
                </td>
                <td>
                  <span class="total_price_per_product small-text <%=order_item.id%>"><%=humanized_money_with_symbol order_item.product.currency_price("#{current_currency}")* order_item.quantity%></span>
                </td>
              </div>
            </div>
          </tr>
          <tr class="spacer"></tr>
        <%end%>
      </table>
      <div class="border-bottom"></div>
      <div class="sub-total col-xs-12">
        <span class="col-xs-8 col-xs-offset-4">
          <span class="sidecart-text">
            Subtotal
          </span>
          <span class="order-total-container">
            <span class="sidecart-number">
              <%=humanized_money_with_symbol current_order.calculate_total("#{current_currency}")%>
            </span>
          </span>
        </span>
      </div>
      <div class="shipping-total col-xs-12">
        <span class="col-xs-8 col-xs-offset-4" id = "shipping-cost-container">
          <span class="sidecart-text">
            Shipping Cost
          </span>
          <span class="order-total-container">
            <span class="sidecart-number" id="shipping-cost-number">
              <%=humanized_money_with_symbol @shipping%>
            </span>
          </span>
        </span>
      </div>
      <div class="total-total col-xs-12">
        <span class="col-xs-8 col-xs-offset-4">
          <span class="sidecart-text" id="total-total-text">
            Total
          </span>
          <span class="order-total-container">
            <span id="total-total-number">
              <%=humanized_money_with_symbol @total%>
            </span>
          </span>
        </span>
      </div>
    </div>
    <div class="shipping-method-address-container">
      <div class="small-screen-shipping-container">
        <div class="section-title-container checkout-title-container">
          <span class="section-title" id="address-checkout-title">Shipping address</span>
        </div>
        <%= link_to order_checkout_path(current_order), class: "btn btn-lg simple-button-black change-address" do %>
          <span class="button-text-black">
            Change Address
          </span>
        <%end%>
        <div class="shipping-address">
          <span class="small-text">
            <%=@address.name%>
          </span>
          <br>
          <span class="small-text">
            <%=@address.line1%>
          </span>
          <span class="small-text">
            <%=@address.line2%>
          </span>
          <br>
          <span class="small-text">
            <%=@address.city%>
          </span>
          <br>
          <span class="small-text">
            <%=@address.zip%>
          </span>
          <br>
          <span class="small-text">
            <%=IsoCountryCodes.find(@address.country).name%>
          </span>
        </div>
      </div>
      <div class="section-title-container checkout-title-container">
        <span class="section-title" id="shipping-method-title">Shipping methods</span>
      </div>
      <%@rates.each do|rate|%>
        <div class="col-xs-12">
          <%= radio_button_tag 'rate', rate[:id], rate[:rate]==@lowest_rate ? true : false, class:"rate-radio", :"data-href"=>current_order.id%>
          <span class="small-text radio-button-text"><%=(rate[:service].split /(?=[A-Z])/).first==="First" ? "Standard" : (rate[:service].split /(?=[A-Z])/).first%> <%=rate[:courier]%> <%=rate[:delivery_days]%> <%if current_order.total_price >= 200 && rate[:rate]==@lowest_rate%><span class="small-text bold">free </span><span class="original-price small-text">(<%=humanized_money_with_symbol rate[:rate]%>)</span><%elsif current_order.total_price >= 200 && rate[:rate]!=@lowest_rate%><span class="small-text bold"><%=humanized_money_with_symbol (rate[:rate]-@lowest_rate)%> </span><span class="original-price small-text">(<%=humanized_money_with_symbol rate[:rate]%>)</span><%else%><span class="small-text bold"><%=number_to_currency rate[:rate]%></span><%end%></span>
        </div>
      <%end%>
      <div class="totals">
        <div class="sub-total">
          <span class="sidecart-text">
            Subtotal
          </span>
          <span class="order-total-container">
            <span class="sidecart-number">
              <%=humanized_money_with_symbol current_order.calculate_total("#{current_currency}")%>
            </span>
          </span>
        </div>
        <div class="shipping-total">
          <span class="" id = "shipping-cost-container">
            <span class="sidecart-text">
              Shipping Cost
            </span>
            <span class="order-total-container">
              <span class="sidecart-number" id="shipping-cost-number">
                <%=humanized_money_with_symbol @shipping%>
              </span>
            </span>
          </span>
        </div>
        <div class="total-total">
          <span class="sidecart-text" id="total-total-text">
            Total
          </span>
          <span class="order-total-container">
            <span id="total-total-number">
              <%=humanized_money_with_symbol @total%>
            </span>
          </span>
        </div>
      </div>
    </div>

    <div class="shipping-container">
      <div class="section-title-container checkout-title-container">
        <span class="section-title" id="address-checkout-title">Shipping address</span>
      </div>
      <%= link_to order_checkout_path(current_order), class: "btn btn-lg simple-button-black change-address", id:"final-checkout" do %>
        <span class="button-text-black">
          Change Address
        </span>
      <%end%>
      <div class="shipping-address">
        <span class="small-text">
          <%=@address.name%>
        </span>
        <br>
        <span class="small-text">
          <%=@address.line1%>
        </span>
        <span class="small-text">
          <%=@address.line2%>
        </span>
        <br>
        <span class="small-text">
          <%=@address.city%>
        </span>
        <br>
        <span class="small-text">
          <%=@address.zip%>
        </span>
        <br>
        <span class="small-text">
          <%=IsoCountryCodes.find(@address.country).name%>
        </span>
      </div>
    </div>
  </div>
</div>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @order.status %>
</p>

<p>
  <strong>Account:</strong>
  <%= @order.account_id %>
</p>

<p>
  <strong>Total price:</strong>
  <%= @order.total_price %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>