config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  resources :categories
  devise_for :admins

  devise_for :users
  resources :users do
    resources :order_items
    resources :orders
  end
  resources :subscriptions, only: [:new, :create]
  get 'thanks', to: 'charges#thanks', as: 'thanks'
  resources :orders do
    get "checkout"
    get "cart"
    get "shipping"
    post "tracking"
  end
  resources :order_items
  resources :addresses
  resources :products do
    get "delete"
    get "delivery"
  end
  match '/update_currency' => 'application#update_currency', as: :update_currency, :via => :get
  resources :images
  resource :cart, only: [:show]
  resources :charges, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/account.rb
class Account < ApplicationRecord
  has_many :orders, dependent: :destroy
  belongs_to :user
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :trackable, :validatable

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy
  has_many :tags, dependent: :destroy
end

app/models/image.rb
class Image < ApplicationRecord
  has_attached_file :photo,
    :path => ":rails_root/public/images/:id/:filename",
    :url  => "/images/:id/:filename"
  belongs_to :product
  validates_attachment_content_type :photo, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :product
  before_save :capitalize_name

private
  def capitalize_name
    self.name.capitalize!
  end
end

app/models/material.rb
class Material < ApplicationRecord
  belongs_to :product

  before_save :capitalize_name

private
  def capitalize_name
    self.name.capitalize!
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items, dependent: :destroy
  before_save :update_total
  before_create :update_status
  has_one :address
  register_currency :sgd


  def calculate_total(currency)
    self.order_items.collect { |item| Money.new(item.product.price, "SGD").exchange_to(currency.upcase) * item.quantity }.sum
  end

  def calculate_sgd_total
    self.order_items.collect { |item| item.product.price * item.quantity }.sum
  end

  def calculate_usd_total
    self.order_items.collect { |item| Money.new(item.product.price, "SGD").exchange_to("USD") * item.quantity }.sum
  end

  private

  def update_status
    if self.status == nil?
      self.status = "In progress"
    end
  end

  def update_total
    current_currency=ApplicationController.helpers.current
    self.total_price = calculate_total(current_currency)
    self.currency_total = current_currency
  end


end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
  has_one :shipment
end

app/models/product.rb
class Product < ApplicationRecord
  require 'eu_central_bank'
  eu_bank = EuCentralBank.new
  Money.default_bank = eu_bank
  monetize :price, :as => "pricer"
  Money.default_bank.update_rates
  register_currency :sgd
  has_many :order_items, dependent: :destroy
  has_many :materials, inverse_of: :product, dependent: :destroy
  accepts_nested_attributes_for :materials, reject_if: :all_blank, allow_destroy: true
  has_many :ingredients, inverse_of: :product, dependent: :destroy
  accepts_nested_attributes_for :ingredients, reject_if: :all_blank, allow_destroy: true
  has_many :sizes, inverse_of: :product, dependent: :destroy
  accepts_nested_attributes_for :sizes, reject_if: :all_blank, allow_destroy: true
  has_many :images, inverse_of: :product, dependent: :destroy
  accepts_nested_attributes_for :images, reject_if: :all_blank, allow_destroy: true
  belongs_to :category
  has_many :tags, :through=> :product_tags
  has_many :product_tags
  accepts_nested_attributes_for :product_tags
  def self.search(search)
    where("name LIKE ? OR ingredients LIKE ? OR materials LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%")
  end

  def currency_price (currency)
    Money.new(self.price,'SGD').exchange_to(currency)
  end
end

app/models/product_tag.rb
class ProductTag < ApplicationRecord
  belongs_to :tag
  belongs_to :product
  accepts_nested_attributes_for :tag
  accepts_nested_attributes_for :product
end

app/models/shipment.rb
class Shipment < ApplicationRecord
  belongs_to :order_item
end

app/models/size.rb
class Size < ApplicationRecord
  belongs_to :product
end

app/models/subscription.rb
class Subscription < ApplicationRecord

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :products, :through=> :product_tags
  has_many :product_tags
  accepts_nested_attributes_for :product_tags
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :account

  after_create :set_account

  def set_account
    user_id = User.last.id
    account = Account.create(user_id: user_id)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @order_item=current_order.order_items.new
    @category=Category.find(params[:category_id])
    @tags=@category.tags
    tag=@category.tags.find(params[:id])
    @items=tag.products
    @categories=Category.all
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
  def retrieve_size_price(size,product_id)
    size_price = Size.where({amount: size, product_id: product_id}).first.price
    return size_price
  end

  def retrieve_size_sku(size, product_id)
    size_sku = Size.where({amount: size, product_id: product_id}).first.sku_id
    return size_sku
  end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/tags/show.html.erb
<ul class="categories row">
  <%@categories.each do |category|%>
    <li class="category"><%= link_to category_path(category), class: "btn btn-primary" do %>
      <%=category.name%>
    <%end%>
    </li>
  <%end%>
</ul>
<ul class="tags row">
  <%@tags.each do |tag|%>
    <li class="tag"><%= link_to category_tag_path(@category,tag), class: "btn btn-primary" do %>
      <%=tag.name%>
    <%end%>
    </li>
  <%end%>
</ul>
<h3> Products under this category </h3>
<% @items.each do |product| %>
  <div class="col-md-4 outside-product">
    <%= link_to product_path(product), remote: true do %>
      <div class="col-md-12" id="product">
        <% if product.featured%>
          <div class="featured">
            <div class="ribbon">Featured</div>
          </div>
        <%end%>
        <% if !product.images.empty?%>
          <%= image_tag(product.images.first.photo.url, :class=>"col-md-12", :id=>"product-image") %>
        <%end%>
        <span class="product-name col-xs-12"><%= product.name %></span>
        <% if product.category_id == "1" %>
          <span class="product-price col-xs-12">Starting from <%= number_to_currency product.sizes.first.price %> - <%=product.sizes.first.amount%>g</span>
        <% else %>
          <span class="product-price col-xs-12"><%= number_to_currency product.price %></span>
        <% end %>
        <div class="description">
          <span><%=product.description%></span>
        </div>
        <% if product.category_id == "1"|| product.category_id=="3" %>
          <span class="ingredient-title">Ingredients</span>
          <ul class="ingredient-list">
            <%product.ingredients.each do |ingredient|%>
              <li><%=ingredient.name%></li>
            <%end%>
          </ul>
        <%end%>
        <div class="row">
          <% if product.category_id == "2"%>
            <span class="stock-title">Stock:</span>
            <span class="stock-amount"><%=product.stock%></span>
          <%end%>
        </div>
        <td><%= link_to "Edit", edit_product_path(product), remote: true, class: "btn btn-default" %></td>
        <td><%= link_to "Show", product_path(product), remote: true, class: "btn btn-default" %></td>
        <td><%= link_to "Delete", product_delete_path(product), remote: true, class: "btn btn-danger" %></td>

        <%if product.category_id!="1"%>
          <%= form_for @order_item do |f| %>
            <%= f.hidden_field :product_id, value: product.id %>
            <%= f.number_field :quantity, :class=>"col-xs-12" %>
            <%= f.submit "Add to cart", :class=>"addToCart col-xs-12" %>
          <% end %>
        <%end%>
      </div>
    <%end%>
  </div>
<% end %>
<div id="product-modal" class="modal"></div>