config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  resources :categories
  devise_for :admins

  devise_for :users
  resources :users do
    resources :order_items
    resources :orders
  end
  resources :subscriptions, only: [:new, :create]
  get 'thanks', to: 'charges#thanks', as: 'thanks'
  resources :orders do
    get "checkout"
    get "cart"
    get "shipping"
    post "tracking"
  end
  resources :order_items
  resources :addresses
  resources :products do
    get "delete"
    get "delivery"
  end
  match '/update_currency' => 'application#update_currency', as: :update_currency, :via => :get
  resources :images
  resource :cart, only: [:show]
  resources :charges, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy
  has_many :tags, dependent: :destroy
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
    fresh_when last_modified: @categories.maximum(:updated_at)
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @order_item=current_order.order_items.new
    @categories=Category.all
    @category=Category.find(params[:id])
    @tags=@category.tags.select("name").group(:name)
    @newest_products=@category.products.last(2)
    # fresh_when last_modified: @category.tags.maximum(:updated_at)
    if params[:sort]== "null"
      @sortBy = "Sort By"
    end

    if params[:id] == '2'
      tagss=[]
      @products1 = []
      if params[:tags]
        if params[:tags] == "0"
        else
          params[:tags].each do |tag|
            tag_object = Tag.find_by({name: tag})
            products = tag_object.products
            products.each do |product|
              @products1.push(product)
            end
          end
        end
      else
        @products1=@category.products.where("(stock > ?)", 0)
      end
      @lowPrice = params[:low] ? params[:low] : 0
      @highPrice = params[:high] ? params[:high] : 400
      @currency = current_currency
      lowPrice = params[:low]&&params[:currency] ? (Money.default_bank.exchange(params[:low], @currency, "SGD")).to_f : 0;
      highPrice = params[:high]&&params[:currency] ? (Money.default_bank.exchange(params[:high], @currency, "SGD")).to_f : 400;

      @products2=Product.where("(price >= ? AND price <= ? AND category_id = ? AND stock > ?)", lowPrice, highPrice, @category.id.to_s, 0)
      @productss=(@products1 & @products2)
    # elsif params[:id] == '3'
    #   @products=Product.where("(price >= ? AND price <= ? AND category_id = ?)", params[:low] ? params[:low] : 0, params[:high] ? params[:high] : 100, @category.id.to_s)
    # else
    #   sizes=Size.where("(price >= ? AND price <= ?)", params[:low] ? params[:low] : 0, params[:high] ? params[:high] : 50)
    #   @products = []
    #   sizes.each do |size|
    #     product=Product.find_by({id: size.product_id})
    #     @products.push(product)
    #   end
    #   @products = @products.uniq
    else
      @productss=Product.where("(category_id = ?)", ((@category.id).to_s))
    end
    if params[:sort].present?
      if params[:sort] === "price"
        if params[:order]== "ascending"
          @productss=@productss.sort_by{|h| h[:price]}
        elsif params[:order]== "descending"
          @productss=@productss.sort_by{|h| h[:price]}.reverse!
        end
      end
      if params[:sort] === "newness"
        if params[:order]== "ascending"
          @productss=@productss.sort_by{|h| h[:created_at]}
        elsif params[:order]== "descending"
          @productss=@productss.sort_by{|h| h[:created_at]}.reverse!
        end
      end
    end
    @products=@productss.paginate(:page => params[:page], :per_page => 6)
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)
    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :desc)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(category) do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :desc %>
    <%= f.text_area :desc %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/_products.html.erb
<%if @products.any?%>
  <% @products.each do |product| %>
    <div class="col-xs-4 outside-product">
      <div class="col-xs-12" id="<%= admin_signed_in? ? 'admin-product' : 'product' %>">
        <%= link_to product_path(product) do %>
          <% if product.featured && product.category_id!="2"%>
            <div class="featured">
              <div class="ribbon">Best Seller</div>
            </div>
          <%end%>
          <div class="row carousel">
            <div id="carouselfor<%=product.id%>" class="carousel slide carouselExampleIndicators" data-interval="false" data-ride="carousel">
              <div class="carousel-inner" role="listbox">
                <% product.images.each_with_index do |image, index| %>
                  <div class="carousel-item item <%=index == 0 ? 'active' : '' %>">
                    <%= image_tag(image.photo.url, :class=>"d-block img-fluid product-image")%>
                  </div>
                <% end %>
              </div>
              <a class="carousel-control left" href="#carouselfor<%=product.id%>" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="carousel-control right" href="#carouselfor<%=product.id%>" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
                <span class="sr-only">Next</span>
              </a>
            </div>
          </div>

          <span class="product-name col-xs-12"><%= product.name %></span>
          <span class="product-price col-xs-12"><%=humanized_money_with_symbol product.currency_price(current_currency) %></span>

          <% if admin_signed_in? %>
            <div class="row">
              <% if product.category_id == "2"%>
                <span class="stock-title">Stock:</span>
                <span class="stock-amount"><%=product.stock%></span>
              <%end%>
            </div>
          <% end %>

          <% if admin_signed_in? %>
            <td><%= link_to "Edit", edit_product_path(product), remote: true, class: "btn btn-default" %></td>
            <td><%= link_to "Show", product_path(product), remote: true, class: "btn btn-default" %></td>
            <td><%= link_to "Delete", product_delete_path(product), remote: true, class: "btn btn-danger" %></td>
          <% end %>
        <%end%>
      </div>
    </div>
  <% end %>
<%else%>
  <span class="text-center">No Products found. Please alter your search criteria</span>
<%end%>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Desc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.desc %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<div class="category-show col-xs-12">
  <div class="topbar">
    <%= image_tag("main-image.jpg", :class => "main-image") %>
    <div class="container topbar-text-container">
      <div class="col-xs-6 topbar-text-div">
        <span class="topbar-text">Intricate, beautiful, you</span>
      </div>
      <div class="col-xs-6 path-links">
        <a href="<%= request.base_url %>/products" class="link_to">
          <span class="button-text">
            Home
          </span>
        </a>
        <span>/</span>
        <a href="<%= request.base_url %>/categories/2/?low=0&high=400&tags%5B%5D=Bracelet&tags%5B%5D=Earring&tags%5B%5D=Necklace&tags%5B%5D=Ring" class="link_to">
          <span class="button-text">
            Shop
          </span>
        </a>
      </div>
    </div>
  </div>
  <div class="col-xs-12">
    <div class="col-xs-2 content-path-links">
      <a href="<%= request.base_url %>/products" class="link_to">
        <span class="content-path-text">
          Home
        </span>
      </a>
      <span class="content-path-text">/</span>
      <a href="<%= request.base_url %>/categories/2/?low=0&high=400&tags%5B%5D=Bracelet&tags%5B%5D=Earring&tags%5B%5D=Necklace&tags%5B%5D=Ring" class="link_to">
        <span class="content-path-text">
          Shop
        </span>
      </a>
    </div>
    <div class="dropdowns col-xs-10">
      <div class="dropdowns-first-row">
        <div class="dropdown dropdown-container" id="dropdown-price-toggle-button">
          <a href="#" class="dropdown-toggle has-dropdown btn btn-lg simple-button-grey" data-toggle="dropdown" role="button" aria-expanded="false"><span class="sort-button-text">
          <span class="sorted-by small-text">Price</span><span class="pull-right"><i class='hi hi-angle-down sort-caret'></i></span></span></a>
          <div class="dropdown-menu pricer-dropdown"role="menu">
            <div class="price-output">
              <span id="dropdown-pricer" data-href = <%=session[:currency]%>><span class="small-text"><%=humanized_money_with_symbol Money.new(@lowPrice, current_currency)%> - <%=humanized_money_with_symbol Money.new(@highPrice, current_currency)%></span></span>
            </div>
            <div class="slider">
              <div id = "dropdown-slider" class="price-slider" data-href = <%=@category.id%>></div>
            </div>
          </div>
        </div>
        <div class="dropdown dropdown-container" id="dropdown-categories-toggle-button">
          <a href="#" class="dropdown-toggle has-dropdown btn btn-lg simple-button-grey" data-toggle="dropdown" role="button" aria-expanded="false"><span class="sort-button-text">
          <span class="sorted-by small-text">Categories</span><span class="pull-right"><i class='hi hi-angle-down sort-caret'></i></span></span></a>
          <div class="dropdown-menu category-dropdown"role="menu">
            <div class="tag-filter">
              <%@tags.each do |tag|%>
                <div class="input-checkbox">
                  <label class="control control--checkbox small-text"><%=tag.name%>s
                		<input type="checkbox" class="dropdown-tag-check-box styled-checkbox" checked id="<%=tag.name%>">
                		<div class="control__indicator"></div>
                	</label>
                </div>
              <%end%>
            </div>
          </div>
        </div>
      </div>
      <div class="dropdowns-second-row">
        <div class="dropdown dropdown-container" id="dropdown-sort-toggle-button">
          <a href="#" class="dropdown-toggle has-dropdown btn btn-lg simple-button-grey" id="sort-by-dropdown" data-toggle="dropdown" role="button" aria-expanded="false"><span class="sort-button-text">
          <span class="sorted-by small-text"><%=@sortBy%></span><span class="pull-right"><i class='hi hi-angle-down sort-caret'></i></span></span></a>
          <ul class="dropdown-menu sorter-dropdown"role="menu">
            <li class="sort-by-option small-text" id="price" data-href="ascending">$-$$$</li>
            <li class="sort-by-option small-text" id="price" data-href="descending">$$$-$</li>
            <li class="sort-by-option small-text" id="newness" data-href="ascending">Newest</li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="sidebar-container">
    <div class="sidebar col-xs-3">
      <div class="filter col-xs-12">
        <div class="sidebar-title-container">
          <span class="sidebar-title small-text">Price</span>
        </div>

        <div class="price-filter col-xs-12">
          <div class="price-output">
            <span id="pricer" data-href = <%=session[:currency]%>><span class="small-text"><%=humanized_money_with_symbol Money.new(@lowPrice, current_currency)%> - <%=humanized_money_with_symbol Money.new(@highPrice, current_currency)%></span></span>
          </div>
          <div class="slider">
            <div id = "slider-3" class="price-slider" data-href = <%=@category.id%>></div>
          </div>
        </div>
        <div class="sidebar-content col-xs-12">
          <div class="sidebar-title-container">
            <span class="sidebar-title small-text">Categories</span>
          </div>
          <div class="tag-filter col-xs-12">
            <%@tags.each do |tag|%>
              <div class="input-checkbox">
                <label class="control control--checkbox small-text"><%=tag.name%>s
              		<input type="checkbox" class="tag-check-box styled-checkbox" checked id="<%=tag.name%>">
              		<div class="control__indicator"></div>
              	</label>
              </div>
            <%end%>
          </div>
        </div>
      </div>
      <div class="newest-products sidebar-content col-xs-12">
        <div class="sidebar-title-container">
          <span class="sidebar-title small-text">Newest Products</span>
        </div>
        <%@newest_products.each do |product|%>
          <%= link_to product_path(product) do %>
            <div class="newest-product col-xs-12">
              <div class="newest-product-image col-xs-5">
                <%= image_tag(product.images.first.photo.url, :id=>"newest-product-image") %>
              </div>
              <div class="newest-product-info col-xs-7">
                <span class="newest-product-name col-xs-12 small-text"><%=product.name%></span>
                <span class="newest-product-price col-xs-12 small-text"><%=humanized_money_with_symbol product.currency_price("#{current_currency}") %></span>
              </div>
            </div>
          <%end%>
        <%end%>
      </div>
      <div class="sidebar-content col-xs-12">
        <div class="sidebar-title-container">
          <span class="sidebar-title small-text">Return Policy</span>
        </div>
        <span class="return-policy normal-text col-xs-12">1 year warranty on all items. We will be happy to cover any replacement/repair cost and ask you to only cover the shipping.</span>
      </div>
    </div>
  </div>
  <div class="products-to-show col-xs-9">
    <div id="productss">
      <%=render 'products'%>
    </div>
  </div>
  <div class="pagination-links small-text">
    <%= will_paginate @products, renderer: BootstrapPagination::Rails %>
  </div>
</div>



<div id="product-modal" class="modal"></div>