config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  resources :categories
  devise_for :admins

  devise_for :users
  resources :users do
    resources :order_items
    resources :orders
  end
  resources :subscriptions, only: [:new, :create]
  get 'thanks', to: 'charges#thanks', as: 'thanks'
  resources :orders do
    get "checkout"
    get "cart"
    get "shipping"
    post "tracking"
  end
  resources :order_items
  resources :addresses
  resources :products do
    get "delete"
    get "delivery"
  end
  match '/update_currency' => 'application#update_currency', as: :update_currency, :via => :get
  resources :images
  resource :cart, only: [:show]
  resources :charges, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/account.rb
class Account < ApplicationRecord
  has_many :orders, dependent: :destroy
  belongs_to :user
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :trackable, :validatable

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy
  has_many :tags, dependent: :destroy
end

app/models/image.rb
class Image < ApplicationRecord
  has_attached_file :photo,
    :path => ":rails_root/public/images/:id/:filename",
    :url  => "/images/:id/:filename"
  belongs_to :product
  validates_attachment_content_type :photo, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :product
  before_save :capitalize_name

private
  def capitalize_name
    self.name.capitalize!
  end
end

app/models/material.rb
class Material < ApplicationRecord
  belongs_to :product

  before_save :capitalize_name

private
  def capitalize_name
    self.name.capitalize!
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items, dependent: :destroy
  before_save :update_total
  before_create :update_status
  has_one :address
  register_currency :sgd


  def calculate_total(currency)
    self.order_items.collect { |item| Money.new(item.product.price, "SGD").exchange_to(currency.upcase) * item.quantity }.sum
  end

  def calculate_sgd_total
    self.order_items.collect { |item| item.product.price * item.quantity }.sum
  end

  def calculate_usd_total
    self.order_items.collect { |item| Money.new(item.product.price, "SGD").exchange_to("USD") * item.quantity }.sum
  end

  private

  def update_status
    if self.status == nil?
      self.status = "In progress"
    end
  end

  def update_total
    current_currency=ApplicationController.helpers.current
    self.total_price = calculate_total(current_currency)
    self.currency_total = current_currency
  end


end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
  has_one :shipment
end

app/models/product.rb
class Product < ApplicationRecord
  require 'eu_central_bank'
  eu_bank = EuCentralBank.new
  Money.default_bank = eu_bank
  monetize :price, :as => "pricer"
  Money.default_bank.update_rates
  register_currency :sgd
  has_many :order_items, dependent: :destroy
  has_many :materials, inverse_of: :product, dependent: :destroy
  accepts_nested_attributes_for :materials, reject_if: :all_blank, allow_destroy: true
  has_many :ingredients, inverse_of: :product, dependent: :destroy
  accepts_nested_attributes_for :ingredients, reject_if: :all_blank, allow_destroy: true
  has_many :sizes, inverse_of: :product, dependent: :destroy
  accepts_nested_attributes_for :sizes, reject_if: :all_blank, allow_destroy: true
  has_many :images, inverse_of: :product, dependent: :destroy
  accepts_nested_attributes_for :images, reject_if: :all_blank, allow_destroy: true
  belongs_to :category
  has_many :tags, :through=> :product_tags
  has_many :product_tags
  accepts_nested_attributes_for :product_tags
  def self.search(search)
    where("name LIKE ? OR ingredients LIKE ? OR materials LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%")
  end

  def currency_price (currency)
    Money.new(self.price,'SGD').exchange_to(currency)
  end
end

app/models/product_tag.rb
class ProductTag < ApplicationRecord
  belongs_to :tag
  belongs_to :product
  accepts_nested_attributes_for :tag
  accepts_nested_attributes_for :product
end

app/models/shipment.rb
class Shipment < ApplicationRecord
  belongs_to :order_item
end

app/models/size.rb
class Size < ApplicationRecord
  belongs_to :product
end

app/models/subscription.rb
class Subscription < ApplicationRecord

end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :products, :through=> :product_tags
  has_many :product_tags
  accepts_nested_attributes_for :product_tags
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :account

  after_create :set_account

  def set_account
    user_id = User.last.id
    account = Account.create(user_id: user_id)
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
  def retrieve_size_price(size,product_id)
    size_price = Size.where({amount: size, product_id: product_id}).first.price
    return size_price
  end

  def retrieve_size_sku(size, product_id)
    size_sku = Size.where({amount: size, product_id: product_id}).first.sku_id
    return size_sku
  end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="footer-div">
    <ul class="nav navbar-nav navbar-left footer-currency-dropdown">
      <li class="dropdown" id="currency-dropdown">
        <a href="javascript:void(0)" class="currency-dropdown-button currency-field small-text"><i class='hi hi-angle-up'></i><%=current_currency%></a>
        <ul class="dropdown-currency-menu">
          <a href="javascript:void(0)" class="closebtn">&times;</a>
          <%major_currencies(Money::Currency.table).each do |currency|%>
            <li class="currency" data-href=<%=currency[:id]%>><span class="small-text currency-symbol"><%=currency[:symbol]%></span><span class="small-text currency-code"><%=currency[:id]%></span></li>
          <%end%>
        </ul>
      </li>
    </ul>
    <span class="firstfooterrow"><span class="made-by small-text">Made by Gabriel Jaeger</span><span class="email-address"><i class="fa fa-envelope general-icon"></i><a href="mailto:support@company.com" class="email-link"><span class="email-address-text small-text">email@gmail.com</span></a></span><span class="address"><i class="fa fa-map-marker general-icon"></i><span class="address-text small-text">63 Beach Road, 50193 Singapore</span></span></span><span class="secondfooterrow"><span class="made-by2 small-text">Made by Gabriel Jaeger</span><span class="copyright small-text">&copy Copyright JewelQueen</span></span></span>
  </div>
</footer>

app/views/layouts/_oldfooter.html.erb
<footer class="footer-distributed" id="contact">

  <div class="footer-left">

    <%=image_tag("logo.png", :class=>"nav-logo")%>

    <p class="footer-links">
      <a href="#">Home</a>
      ·
      <a href="#">How it works</a>
      ·
      <a href="#">Contact</a>
    </p>

    <p class="footer-company-name">Hexagon innovation &copy; 2017</p>
    <div class="footer-icons">

      <a href="#"><i class="fa fa-facebook"></i></a>
      <a href="#"><i class="fa fa-twitter"></i></a>
      <a href="#"><i class="fa fa-linkedin"></i></a>
      <a href="#"><i class="fa fa-github"></i></a>

    </div>
  </div>

  <div class="footer-center">

    <div>
      <i class="fa fa-map-marker general-icon"></i>
      <p><span>1 Some Street</span> Melbourne, Australia</p>
    </div>

    <div>
      <i class="fa fa-phone general-icon"></i>
      <p>+6 401 203 391</p>
    </div>

    <div>
      <i class="fa fa-envelope general-icon"></i>
      <p><a href="mailto:support@company.com">support@hexinnov.com</a></p>
    </div>



  </div>
  <div class="footer-right">

    <p>Contact Us</p>

    <form action="#" method="post">

      <input type="text" name="email" placeholder="Email" />
      <textarea name="message" placeholder="Message"></textarea>
      <button>Send</button>

    </form>

  </div>

</footer>

app/views/layouts/_shopping_cart.html.erb
<% if current_order_items!=nil && current_order_items.any? %>
  <div class="order-items-list">
    <% current_order_items.each do |item| %>
      <li>
        <span class="order-item" id="order-item">
          <%=link_to product_path(item.product), :class=>"" do%>
            <span class="col-xs-12 shopping-cart-row">
              <%= image_tag(item.product.images.first.photo.url, :class=> "cart-item-image") %>
              <span class="item-info">
                <span class="cart-product-name", id="cart-product-name", data-href = <%=item.product.id%>><%= item.product.name%></span>
                <span class="cart-product-price", id="cart-product-price", data-href=<%=item.quantity%>>
                  <%=humanized_money_with_symbol (item.product.currency_price("#{current_currency}"))*item.quantity %>
                </span>
                <span id="cart-product-quantity">Qty.: <%=item.quantity%></span>
                <span id="cart-product-size">Size: <%=item.product.length%>cm</span>
                <span class="last-row">
                  <span id="cart-product-single-price">Price: <%=humanized_money_with_symbol item.product.currency_price(current_currency)%></span>
                  <%=link_to order_item_path(item), :data => {:method => "delete"}, remote: true, :class =>"delete_order_item" do%>
                    <span class="remove-text"><i class="fa fa-trash" aria-hidden="true"></i></span>
                  <%end%>
                </span>
              </span>
            </span>
          <% end %>
          <span class="item-right">
          </span>
        </span>
      </li>
    <%end%>
  </div>
  <div class="total-and-shipping col-xs-12">
    <span class="total-container col-xs-12">
      <span class="total-cart-text">Total:</span>
      <span class="total-cart-number"><%=humanized_money_with_symbol current_order.calculate_total("#{current_currency}")%></span>
    </span>
    <span class="shipping-container col-xs-12">
      <span class="shipping-cart-text">Shipping:</span>
      <span class="shipping-cart-number"><%if current_order.calculate_usd_total>= freeShippingAmountUSD%>Free<%else%>Calculated at Checkout<%end%></span>
    </span>
  </div>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ecommerce</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= javascript_include_tag :jquery %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker.min.css" />
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <link href = "https://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css" rel = "stylesheet">
    <link rel="stylesheet" href="https://cdn.hippicons.com/css/hippicons-min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jqueryui-touch-punch/0.2.3/jquery.ui.touch-punch.min.js"></script>
    <script src="https://use.fontawesome.com/4430b10b2e.js"></script>
    <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
    <script src='https://s3-us-west-2.amazonaws.com/s.cdpn.io/121761/card.js'></script>
    <script src='https://s3-us-west-2.amazonaws.com/s.cdpn.io/121761/jquery.card.js'></script>
    <script type="text/javascript">
      Stripe.setPublishableKey('<%= Rails.configuration.stripe[:publishable_key] %>');
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.13.0/moment.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar-fixed-top" id="navbar">
        <ul class="nav navbar-nav navbar navbar-center">
          <li class="navbar-logo-container">
            <%= link_to products_path, class:"logo-link" do%><%= image_tag("logo.jpg", :class=> "navbar-logo") %><%end%>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-left currency-dropdown">
          <li class="dropdown" id="currency-dropdown">
            <a href="javascript:void(0)" class="currency-dropdown-button currency-field small-text"><%=current_currency%><i class='hi hi-angle-down'></i></a>
            <ul class="dropdown-currency-menu">
              <a href="javascript:void(0)" class="closebtn">&times;</a>
              <%major_currencies(Money::Currency.table).each do |currency|%>
                <li class="currency" data-href=<%=currency[:id]%>><span class="small-text currency-symbol"><%=currency[:symbol]%></span><span class="small-text currency-code"><%=currency[:id]%></span></li>
              <%end%>
            </ul>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-left small-screen-dropdown-menu">
          <li class="dropdown" id="dropdown-menu-button">
            <a href="#" class="dropdown-toggle has-dropdown dropdown-menu-button" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-bars" aria-hidden="true"></i></a>
            <ul class="dropdown-menu no-collapse dropdown-menu-nav"role="menu">
              <li><%= link_to products_path do%><span class="small-text">Home</span><%end%></li>
              <li>
                <a href="<%= request.base_url %>/categories/2/?low=0&high=400&tags%5B%5D=Bracelet&tags%5B%5D=Earring&tags%5B%5D=Necklace&tags%5B%5D=Ring"><span class="shop-dropdown small-text">Shop</span></span></a>
              </li>
            </ul>
          </li>
        </ul>


        <ul class="nav navbar-nav home-navbar-button">
          <li><%= link_to products_path do%><span class="small-text">Home</span><%end%></li>
          <%if admin_signed_in?%>
            <li><%= link_to 'All Orders', orders_path() %></li>
          <%end%>
        </ul>
            <!-- <%= form_tag(products_path, :method => "get", id: "search-form", class: "navbar-form navbar-left") do %>
              <div class="form-group">
                <%= text_field_tag :search, params[:search], placeholder: "Search Products", class: "form-control" %>
              </div>
              <%= submit_tag "Search", :name => nil, :class => "btn btn-default" %>
            <% end %> -->
        <ul class="nav navbar-nav shop-navbar-button">
          <li>
            <a href="<%= request.base_url %>/categories/2/?low=0&high=400&tags%5B%5D=Bracelet&tags%5B%5D=Earring&tags%5B%5D=Necklace&tags%5B%5D=Ring"><span class="shop-dropdown small-text">Shop</span></span></a>
          </li>
        </ul>

        <ul class="nav navbar-nav navbar-right dropdown-button-container">
          <li class="dropdown" id="dropdown-cart-button">
            <a href="#" class="dropdown-toggle has-dropdown dropdown-button dropdown-toggle-cart" data-toggle="dropdown" role="button" aria-expanded="false"><span class="cart-dropdown" id="order-total-container">
            <span class="glyphicon glyphicon-shopping-cart"></span><span class="item-count"><%=current_order.order_items.sum(:quantity)%></span><i class='hi hi-angle-down'></i></span></a>
            <ul class="dropdown-menu no-collapse dropdown-cart"role="menu">
              <div class="shopping-cart">
                <%= render "layouts/shopping_cart" %>
              </div>

              <div class="empty-cart-div">
              </div>

              <div class="checkout-button-div">
              </div>

              <% if current_order_items==nil || !current_order_items.any? %>
                <li>
                  <span class="empty-cart">
                    <span class="small-text">Your shopping cart is empty.</span>
                  </span>
                  <div class="total-and-shipping col-xs-12">
                    <span class="total-container col-xs-12">
                      <span class="total-cart-text">Total:</span>
                      <span class="total-cart-number"><%=humanized_money_with_symbol Money.new(0,current_currency)%></span>
                    </span>
                    <span class="shipping-container col-xs-12">
                      <span class="shipping-cart-text">Shipping:</span>
                      <span class="shipping-cart-number"><%if current_order.calculate_usd_total>= freeShippingAmountUSD%>Free<%else%>Calculated at Checkout<%end%></span>
                    </span>
                  </div>
                </li>
              <%end%>
              <%if current_order_items!=nil && current_order_items.any?%>
                <div class="checkout-button">
                  <%= link_to order_cart_path(current_order), class: "btn btn-lg simple-button-black", id:"checkout-button" do %>
                    <span class="button-text-black" id="x-text">
                      Proceed to checkout<i class='hi hi-angle-right proceed-icon'></i>
                    </span>
                  <%end%>
                </div>
              <% end %>
            </ul>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if admin_signed_in? %>
            <li><%= link_to 'Edit profile', edit_admin_registration_path %></li>
            <li><%= link_to 'Logout Admin', destroy_admin_session_path, method: :delete%></li>
          <% end%>
        </ul>
      </nav>
    </header>
    <div class="yield-container">
      <%= yield %>
    </div>

  </body>
  <%= render "layouts/footer" %>
  <div class="spinner">
    <div class="sk-cube-grid">
      <div class="sk-cube sk-cube1"></div>
      <div class="sk-cube sk-cube2"></div>
      <div class="sk-cube sk-cube3"></div>
      <div class="sk-cube sk-cube4"></div>
      <div class="sk-cube sk-cube5"></div>
      <div class="sk-cube sk-cube6"></div>
      <div class="sk-cube sk-cube7"></div>
      <div class="sk-cube sk-cube8"></div>
      <div class="sk-cube sk-cube9"></div>
    </div>
  </div>

  <div class="shipping-spinner">
    <div class="cube-grid-wrapper">
      <div class="sk-cube-grid">
        <div class="sk-cube sk-cube1"></div>
        <div class="sk-cube sk-cube2"></div>
        <div class="sk-cube sk-cube3"></div>
        <div class="sk-cube sk-cube4"></div>
        <div class="sk-cube sk-cube5"></div>
        <div class="sk-cube sk-cube6"></div>
        <div class="sk-cube sk-cube7"></div>
        <div class="sk-cube sk-cube8"></div>
        <div class="sk-cube sk-cube9"></div>
      </div>
    </div>
    <div class="shipping-text-wrapper">
      <span class="shipping-text">Calculating Shipping Cost...</span>
    </div>
  </div>

</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/order_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ecommerce</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker.min.css" />
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <link href = "https://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css" rel = "stylesheet">
    <link rel="stylesheet" href="https://cdn.hippicons.com/css/hippicons-min.css">
    <script src="https://use.fontawesome.com/4430b10b2e.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
    <script src='https://s3-us-west-2.amazonaws.com/s.cdpn.io/121761/card.js'></script>
    <script src='https://s3-us-west-2.amazonaws.com/s.cdpn.io/121761/jquery.card.js'></script>
    <script type="text/javascript">
      Stripe.setPublishableKey('<%= Rails.configuration.stripe[:publishable_key] %>');
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.13.0/moment.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar-fixed-top" id="navbar">
        <ul class="nav navbar-nav navbar-left currency-dropdown">
          <li class="dropdown" id="currency-dropdown">
            <a href="javascript:void(0)" class="currency-dropdown-button currency-field small-text"><%=current_currency%><i class='hi hi-angle-down'></i></a>
            <ul class="dropdown-currency-menu">
              <a href="javascript:void(0)" class="closebtn">&times;</a>
              <%major_currencies(Money::Currency.table).each do |currency|%>
                <li class="currency" data-href=<%=currency[:id]%>><span class="small-text currency-symbol"><%=currency[:symbol]%></span><span class="small-text currency-code"><%=currency[:id]%></span></li>
              <%end%>
            </ul>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar navbar-center">
          <li>
            <%= link_to products_path, class:"logo-link" do%><span><%= image_tag("logo.jpg", :class=> "navbar-logo") %></span><%end%>
          </li>
        </ul>
      </nav>
    </header>
    <div class="yield-container">
      <%= yield %>
    </div>
  </body>
  <%= render "layouts/footer" %>
  <div class="spinner">
    <div class="sk-cube-grid">
      <div class="sk-cube sk-cube1"></div>
      <div class="sk-cube sk-cube2"></div>
      <div class="sk-cube sk-cube3"></div>
      <div class="sk-cube sk-cube4"></div>
      <div class="sk-cube sk-cube5"></div>
      <div class="sk-cube sk-cube6"></div>
      <div class="sk-cube sk-cube7"></div>
      <div class="sk-cube sk-cube8"></div>
      <div class="sk-cube sk-cube9"></div>
    </div>
  </div>

  <div class="shipping-spinner">
    <div class="cube-grid-wrapper">
      <div class="sk-cube-grid">
        <div class="sk-cube sk-cube1"></div>
        <div class="sk-cube sk-cube2"></div>
        <div class="sk-cube sk-cube3"></div>
        <div class="sk-cube sk-cube4"></div>
        <div class="sk-cube sk-cube5"></div>
        <div class="sk-cube sk-cube6"></div>
        <div class="sk-cube sk-cube7"></div>
        <div class="sk-cube sk-cube8"></div>
        <div class="sk-cube sk-cube9"></div>
      </div>
    </div>
    <div class="shipping-text-wrapper">
      <span class="shipping-text">Calculating Shipping Cost...</span>
    </div>
  </div>
  <div class="circle-spinner">
    <div class="sk-circle-wrapper">
      <div class="sk-circle">
        <div class="sk-circle1 sk-child"></div>
        <div class="sk-circle2 sk-child"></div>
        <div class="sk-circle3 sk-child"></div>
        <div class="sk-circle4 sk-child"></div>
        <div class="sk-circle5 sk-child"></div>
        <div class="sk-circle6 sk-child"></div>
        <div class="sk-circle7 sk-child"></div>
        <div class="sk-circle8 sk-child"></div>
        <div class="sk-circle9 sk-child"></div>
        <div class="sk-circle10 sk-child"></div>
        <div class="sk-circle11 sk-child"></div>
        <div class="sk-circle12 sk-child"></div>
      </div>
    </div>
  </div>
  <div class="circle-spinner2">
    <div class="sk-circle-wrapper">
      <div class="sk-circle">
        <div class="sk-circle1 sk-child"></div>
        <div class="sk-circle2 sk-child"></div>
        <div class="sk-circle3 sk-child"></div>
        <div class="sk-circle4 sk-child"></div>
        <div class="sk-circle5 sk-child"></div>
        <div class="sk-circle6 sk-child"></div>
        <div class="sk-circle7 sk-child"></div>
        <div class="sk-circle8 sk-child"></div>
        <div class="sk-circle9 sk-child"></div>
        <div class="sk-circle10 sk-child"></div>
        <div class="sk-circle11 sk-child"></div>
        <div class="sk-circle12 sk-child"></div>
      </div>
    </div>
  </div>


</html>